import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className + ' max-w-4xl p-10 mx-auto'}>
        <nav className='flex gap-4 justify-start mb-8 prose dark:prose-invert'>
          <Link href='/'>home</Link>
          <Link href='/work'>work</Link>
          <Link href='/showcase'>showcase</Link>
          <Link href='/devlog'>devlog</Link>
        </nav>

        {children}
      </body>
    </html>
  )
}
